language: node_js
node_js:
- 8.4.0
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
- export PATH="$HOME/.yarn/bin:$PATH"
after_success:
- npm run coveralls
notifications:
  slack:
    secure: lOdT9rVCNyAl7+cmhXrNGmiQP5+9QyUqstIF1NerPf0gYXvO6yUXaaQhyhK7lJpHnq1cFFnncjq6jzrry5Ez4mbXLkRpX8K/iO74pOsPN8hP6jrj3Z+C/TTEBWE21MACSo+fC+Fp+56nb+uj7b3iMfD0VgpAMGgRBaMD61Y1hwsD4OsLjh3gYx+VM3IkCDMUS9pyIi6m9F/7kvVJqPPn60pAoOE1ooJ35igMKmrOVwChwpOU7+TIcP/ma9GsSRZJRl7MYJw6CKixaepaqFkycg8DjgFbYdQUXji72v3b63hqdxI6qwMRxVBHOhq7021T/7Wl54SbpMIx23dVNRU6QsHilm6dxQ9Axdr+NR4ra/lQmcGU5e6vvvKbbiQN4YvQGnIa5EOE8/IcNXPtf00YyTomOrFUFE5Br6misBmmB1jYDH/4mSIezrdYxu+o4m7ZfZ4UDnhHJDW9x8r1hlAG4SxyH6Cc2geeCB1NWw+868Ur4qxHfwMeheQXoQEwI3i3BCIT4gEaMEzbsFLxGm7ci3Z2SKt58c02647KkGsdB9ftyC/FDcHtTm/Ox8PuCz/0J/KqFlQ40bLpocCwVhWWUq58/l92iQet2on34l1tI3vbnQBl4Xn6GUWKSwTkK3JbfUFYdtj8GEvEbVWByF5DCxLgALdbw9oqWhfC8srgCpk=
